### ISSUE TITLE
Make ObjectPerturbator return valid or invalid JSON by choice

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#108]
This implies several things:
  - Remove the checkFaulty() call from the test case generators and move that logic into the ObjectPerturbator.
  - Set a maximum number of tries (sometimes it may be impossible to return an invalid JSON).

**Comment by ssegura** [comment]
This is a critical issue. When generating test cases for Amadeus (Hotel search) with faultyRatio=0.1, 100% of the generated tests are faulty. I will wait until this is fixed before continuing with the tests of the constraint-based test case generator.

**Comment by ssegura** [comment]
There is no easy way to validate a JSON object agains an OAS Schema. As a workaround, we now check whether the perturbation is valid or not in the class AbstractTestCaseGenerator (method generateRandomTestCase). If not, the original object (provided in the test configuration file) is used for the test.
