### ISSUE TITLE
Create script to run all APIs from benchmark at once

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#11]
Right now, the way to run the bechmark APIs is to go one by one in Eclipse/IntelliJ and press the start button. It would be nice to have something to run all of them at once. It would be even nicer if they could be run as a background process (for the server betty.us.es),

The same thing applies to RESTest execution. It would be great to have a script where to select the APIs that want to be tested, and run it as a background process.

**Comment by ssegura** [comment]
Juan Carlos will take care of this. I will close this until then as it has low priority.
