### ISSUE TITLE
"The test case generated does not conform to the specification"

### ISSUE THREAD

**Issue by amedeoz** [isa-group/RESTest#166]
[logs.tar.gz](https://github.com/isa-group/RESTest/files/5795909/logs.tar.gz)
[logs2.tar.gz](https://github.com/isa-group/RESTest/files/5795912/logs2.tar.gz)

During some testing with RESTest on two different REST services I got this error: `The test case generated does not conform to the specification`. In both cases I tried to fix these problems following the error prompts. Anyway the modifications led me to another problem: `Target host is null`.

To be as clear as possible, I am attaching the swagger specifications, all the configuration files (both original and "fixed") and the execution logs.

Am I doing something wrong, or is this behavior caused by a bug?

**Comment by josferde5** [comment]
The swagger spec is not properly configured:

````yaml
swagger: '2.0'
info:
  version: '1.0'
  title: video API
host: 'http://localhost:9090'
basePath: /
paths: 
...
````
This is the description of the ``host`` parameter:

> The host (name or ip) serving the API. This **MUST be the host only and does not include the scheme nor sub-paths**. It MAY include a port. If the host is not included, the host serving the documentation is to be used (including the port). The host does not support path templating.

You have to change the ``host`` parameter to ``localhost:9090`` and include the ``schemes`` parameter:
````yaml
swagger: '2.0'
info:
  version: '1.0'
  title: video API
host: localhost:9090
schemes:
  - http
basePath: /
paths: 
...
````
That should work.

**Comment by amedeoz** [comment]
I made the changes that you suggested, and now the `Target host is null` is fixed, but I keep getting the `The test case generated does not conform to the specification` exception if I do not modify the `testConf.yaml` file.

**Comment by josferde5** [comment]
Unfortunately, RESTest can't generate values for body parameters if the definition object in the Swagger spec - ``User`` in this case - doesn't include a body example in the ``example`` parameter. When you use RESTest to generate a test configuration file, it sets default values - ``value 1`` and ``value 2`` - if it can't infer any data for a parameter. We want to create smarter generators to offer you a better test configuration file generator.

Meanwhile, you can use [our wiki](https://github.com/isa-group/RESTest/wiki/Test-configuration-files) to extend and improve your test configuration file.
