### ISSUE TITLE
Create CoordinatesTestDataGenerator

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#168]
This generator should create realistic coordinates (pairs of floats), i.e., not in the ocean. Maybe there's some Java library already that we can use.

Several parameters could be used, such as:
  - `continent`. If not specified, generate for the whole world.
  - `latLonSep`: the character used between the latitude and longitude. Defaults to ','.
  - `noOfCoord`: the number of coordinates to generate. Defaults to 1.
  - `coordSep`: when generating multiple coordinates, the character used to separate them. Defaults to ';'.

**Comment by antonioruizcortes** [comment]
There is most likely a java library to do it. I came across a Python one the other day (https://github.com/toddkarin/global-land-mask) just in case.
