### ISSUE TITLE
API authentication

### ISSUE THREAD

**Issue by amedeoz** [isa-group/RESTest#171]
I am testing an API that requires authentication (JWT token as a header field). How can I enable authentication in RESTest?

**Comment by josferde5** [comment]
You have to set the authentication parameters in the test configuration file. In this case, as it is a header field:

````yaml
auth:
  required: true
  headerParams:
    - name: Authorization
       value: Bearer <JWT Token>
testConfiguration:
  operations:
# ...
````

**Comment by amedeoz** [comment]
I did as follows:

1. I generated the configuration file. This was the original output:
```yaml
---
auth:
  required: true
  queryParams: {}
  headerParams: {}
  apiKeysPath: null
  headersPath: null
testConfiguration:
  operations:
# ...
```
2. I modified the configuration file with the following:
```yaml
---
auth:
  required: true
  headerParams:
  - name: Authorization
    value: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIU...
testConfiguration:
  operations:
# ...
```

But I keep getting the following error:
```
ERROR TestConfigurationIO:66 - Error parsing configuration file: Cannot deserialize instance of `java.util.LinkedHashMap<java.lang.Object,java.lang.Object>` out of START_ARRAY token
 at [Source: (File); line: 5, column: 3] (through reference chain: es.us.isa.restest.configuration.pojos.TestConfigurationObject["auth"]->es.us.isa.restest.configuration.pojos.Auth["headerParams"])
Exception in thread "main" java.lang.NullPointerException
	at es.us.isa.restest.generators.AbstractTestCaseGenerator.preconditions(AbstractTestCaseGenerator.java:114)
	at es.us.isa.restest.generators.AbstractTestCaseGenerator.<init>(AbstractTestCaseGenerator.java:61)
	at es.us.isa.restest.generators.RandomTestCaseGenerator.<init>(RandomTestCaseGenerator.java:29)
	at es.us.isa.restest.main.TestGenerationAndExecution.createGenerator(TestGenerationAndExecution.java:123)
	at es.us.isa.restest.main.TestGenerationAndExecution.main(TestGenerationAndExecution.java:72)

```
I even tried with different code indentations and keeping the removed lines (i.e. ` queryParams: {}`, `apiKeysPath: null`, `headersPath: null`), but the error is always the same.

I am currently using the release drop package `v0.1.0`.

**Comment by josferde5** [comment]
I just realized the ['Authentication data' section of the wiki](https://github.com/isa-group/RESTest/wiki/Test-configuration-files#authentication-data) is outdated as we changed the format of ``headerParams`` and ``queryParams`` parameters some time ago. This will work:
````yaml
auth:
  required: true
  headerParams:
    Authorization: "Bearer <JWT Token>"
testConfiguration:
  operations:
# ...
````
I will update the wiki documentation as soon as possible.

**Comment by josferde5** [comment]
Besides, you can use an external JSON file to store the API credentials. We recommend this option if you want to use more than one different token for the same parameter. This should be the format of the JSON file:
````json
{
  "APIKEY_PARAMETER_NAME_1": [
  "APIKEY_VALUE_1",
  "APIKEY_VALUE_2",
  "APIKEY_VALUE_3"
  ]
}
````
You need to put the path to the JSON file in the ``apiKeysPath`` parameter (for query fields) or the ``headersPath`` parameter (for header fields).

And thanks for reporting the error!

**Comment by amedeoz** [comment]
> I just realized the ['Authentication data' section of the wiki](https://github.com/isa-group/RESTest/wiki/Test-configuration-files#authentication-data) is outdated as we changed the format of `headerParams` and `queryParams` parameters some time ago. This will work:
> 
> ```yaml
> auth:
>   required: true
>   headerParams:
>     Authorization: "Bearer <JWT Token>"
> testConfiguration:
>   operations:
> # ...
> ```
> 
> I will update the wiki documentation as soon as possible.

I tried this solution and it works. Thanks.
