### ISSUE TITLE
Add docker and a makefile

### ISSUE THREAD

**Issue by robert-fahey** [isa-group/RESTest#176]
It would great if the project had a dockerfile for the main project, a docker-compose with an example API and Restest. A makefile would simplify the execution, test config creation etc. 
I'm putting this together atm I'll try and create a PR once it's working nicely

**Comment by AML14** [comment]
Hi @robert-fahey 

Sorry for the late reply and thanks a lot for your interest in our tool. You're absolutely right, it'd be nice to have something like that. Unfortunately, we usually deal with much more urgent features and have less time for issues concerning the usability of the tool (although they are equally important...).

If you open the project with IntelliJ and run the main file, RESTest should be built automatically and you should be generating tests for the [BikeWise API](https://bikewise.org/), a very simple API that we use for illustration purposes.

In any case, if you feel like addressing this issue yourself and creating a PR, that would be awesome. Let us know if we can help.

**Comment by jackbilestech** [comment]
@robert-fahey Did you get anywhere with this? Currently looking at this as a solution and wanted to see what you had so far.
