### ISSUE TITLE
OneOf not handled in yaml verification

### ISSUE THREAD

**Issue by dlarsen-chwy** [isa-group/RESTest#178]
Trying to verify a yaml file with oneOf property and that is not handled in the verification check, is there a timeline as to when that might be added?

**Comment by AML14** [comment]
What do you mean by "is not handled in the verification check"? I assume you're talking about some response body schema, aren't you? Is it a problem with RESTest crashing or not behaving as expected?

**Comment by dlarsen-chwy** [comment]
When running the test getting this error message back: `OAS disconformity: [Path '/zones/0'] Object has missing required properties (["id"]); [Path '/zones/0/components/0'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type"]; [Path '/zones/0/components/0'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/1'] Object has missing required properties (["id"]); [Path '/zones/1/components/0'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type"]; [Path '/zones/1/components/0'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/1/components/1'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type","useDivider"]; [Path '/zones/1/components/1'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/1/components/2'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type"]; [Path '/zones/1/components/2'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/1/components/3'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type"]; [Path '/zones/1/components/3'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/2'] Object has missing required properties (["id"]); [Path '/zones/2/components/0'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type"]; [Path '/zones/2/components/0'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/2/components/1'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","images","link","type"]; [Path '/zones/2/components/1'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/2/components/2'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type","useDivider"]; [Path '/zones/2/components/2'] Instance failed to match exactly one schema (matched 0 out of 8); [Path '/zones/2/components/3'] Object instance has properties which are not allowed by the schema: ["analytics","header","id","items","type","useDivider"]; [Path '/zones/2/components/3'] Instance failed to match exactly one schema (matched 0 out of 8)`.     From what I can tell the contract is valid so I don't think I should be getting the error. The 0 out of 8 is part of a oneOf section

**Comment by AML14** [comment]
We actually use an external library for the validation of the responses with respect to the Swagger schema: https://bitbucket.org/atlassian/swagger-request-validator/src/master/

Therefore, I'm not entirely sure this is a problem with RESTest, but maybe with the library. You could try using the library in isolation with that specific response that triggers the unexpected behavior.

Also, you can take a look at the issues containing the keyword "oneOf": https://bitbucket.org/atlassian/swagger-request-validator/issues?q=oneof. They may be of some help.

Let me know what you find out.
