### ISSUE TITLE
x-dependencies in test resource

### ISSUE THREAD

**Issue by codingsoo** [isa-group/RESTest#179]
Hi, I want to use the test cases in your resource directory.

Are they have x-dependencies in their swagger files?

For example, in some tests (e.x.Youtube), I can find x-dependencies, but I cannot find for some other cases (e.x. features-service).

Does it mean features-service does not have the x-dependencies?

**Comment by AML14** [comment]
"x-dependencies" is an OpenAPI (OAS) extension we created to specify inter-parameter dependencies (e.g., if you use parameter `A`, then you must also use parameter `B`).

Some of the APIs we test have inter-parameter dependencies, some of them don't. You are right, YouTube contains dependencies, but features-service does not.

Some other examples of API operations that contain dependencies:
- Foursquare - `GET /venues/search` (file Foursquare/swagger.yaml)
- YouTube - `GET /youtube/v3/commentThreads` (file YouTube/openapi.yaml)
- YouTube - `GET /youtube/v3/videos` (file YouTube/openapi.yaml)
- Yelp - `GET /businesses/search` (file Yelp/swagger.yaml)
- Stripe - `POST /v1/coupons` (file Stripe/spec3.yaml)
- Stripe - `POST /v1/products` (file Stripe/spec3.yaml)

If you do a global search of the keyword "x-dependencies" on the root folder of the project, you will find more examples.

Hope this answer helps.
