### ISSUE TITLE
Inter-parameter dependency issue

### ISSUE THREAD

**Issue by qixin5** [isa-group/RESTest#180]
Hi RESTest authors,

Thanks for making the tool available! 

I'm using RESTest to produce test cases for Languagetool (from https://github.com/EMResearch/EMB) which you may be aware of. In the swagger file, I put dependency specification like "OnlyOne(text, data)", but it turns out RESTest still produced tests whose inputs do not follow such dependencies. I wonder if I missed anything?

I provided a package including the swagger file, the running scripts, etc. [here](https://drive.google.com/file/d/1Y9AYEWkxlyUTyAg-m8MRsf9utaKAoPsA/view?usp=sharing) to reproduce this issue. If you need anything else, please let me know. Thanks!

**Comment by AML14** [comment]
Hi @qixin5,

Thanks for your interest in our tool.

I assume you are running RESTest via the shell script you provide in the package, right? In that case, and as you have configured RESTest execution with the "api.properties" file, you are generating 40% of faulty test cases, 50% of which (i.e., 20% of the total test cases) are test cases violating the dependencies specified in Swagger:

```properties
# Ratio of faulty test cases to be generated (negative testing)
faulty.ratio=0.4

# CONFIGURATION SETTINGS FOR CONSTRAINT-BASED TESTING

# Ratio of faulty test cases to be generated due to broken dependencies.
faulty.dependency.ratio=0.5
```

If you want to produce only valid test cases (i.e., test cases using valid input data and satisfying all dependencies), you can specify it as follows: `faulty.ratio=0`

If you want to know more about RESTest configuration files, take a look at the following section of the Wiki: https://github.com/isa-group/RESTest/wiki/RESTest-configuration-files

**Comment by qixin5** [comment]
Hi @AML14, yes I'm using RESTest via shell script. I see, and thanks for your reply!
