### ISSUE TITLE
Does RESTest support swagger2.0 OAS  for json file types

### ISSUE THREAD

**Issue by painsAgains** [isa-group/RESTest#226]
Hello，
I would like to know if RESTestest can automatically handle OAS of json file type，like：`openapi.json`
I tried the json OAS，but I found it does not work:
![image](https://user-images.githubusercontent.com/49607803/192446614-f426f700-1059-4a7b-8be8-6aee7328e51a.png)
My` CreateTest `class 、`TestGenerationAndExecution c`lass and `properties` file as :
![image](https://user-images.githubusercontent.com/49607803/192447059-55776653-2409-421e-ae8c-1bcae4e8b720.png)
![image](https://user-images.githubusercontent.com/49607803/192447118-ddb04889-e48a-4560-949e-213b60739bbc.png)
![image](https://user-images.githubusercontent.com/49607803/192447171-34824ebd-413b-4bc3-86f5-fb25293b6fd4.png)

If anyone can help me, I would appreciate it
Thanks！

**Comment by AML14** [comment]
Hi,

RESTest does support OAS files in JSON, as well as YAML, of course. The error that you show seems to be related to a problem with the OpenAPI document itself, as dictated by the OpenAPI parser library that we use. In particular, it looks like your OpenAPI JSON document lacks the `openapi` keyword (or the `swagger` keyword if you are using OAS 2.0).

I tried running the CreateTestConf main class with the file located at `src/test/resources/BigOven/spec.json` and it worked fine for me.
