### ISSUE TITLE
es.us.isa.restest.inputs.stateful.BodyGenerator.generateStatefulObjectNode does not judge the Null value for 'schema' variable

### ISSUE THREAD

**Issue by painsAgains** [isa-group/RESTest#227]
When I test my spec I found when 'schema' in spec is null, The RESTest can't filter this situation,and it will report a error like this:

![image](https://user-images.githubusercontent.com/49607803/196138383-a5e51f87-208a-4e7d-9eda-2ec1a9909de0.png)

 So I check the 107 line in es.us.isa.restest.inputs.stateful.BodyGenerator.generateStatefulObjectNode，Then I found the variable **_'schema'_**  does not make a null judgment
![image](https://user-images.githubusercontent.com/49607803/196138566-86dd0572-99b1-4e35-b10b-df01657b5e3c.png)
When I add null value judgment(of cause you can add try catch), it works again

![image](https://user-images.githubusercontent.com/49607803/196140161-c10db94e-3963-4689-81f9-31ee453d4b92.png)

**Comment by AML14** [comment]
Thanks for the report. If you want, you can submit a PR including this change and a corresponding test that checks that the functionality is implemented as expected (i.e., including an OpenAPI with a null schema and asserting that no exception is thrown).
