### ISSUE TITLE
How to add cert file ,key file and disable TLS certificate validation during the SSL handshake

### ISSUE THREAD

**Issue by painsAgains** [isa-group/RESTest#229]
I reviewed the wiki,and I just found three methods  to pass auth `API key,Bear token and HTTP Basic`
But when I test my api,I should provid cert file , private key file and disable TLS certificate walidation  during the SSL handshark,like this
`curl https://xxx/api/v1 -k --cert filename.crt --key file.key`

 Does RESTest currently implement this functionality?
Really hope somebody can help me.
Thanks!

**Comment by AML14** [comment]
RESTest does not currently support authentication like this and I don't think we will support it in the near future, as it is not something common at all in REST APIs. If you want to submit a PR implementing this functionality, you are more than welcome.

**Comment by painsAgains** [comment]
> RESTest does not currently support authentication like this and I don't think we will support it in the near future, as it is not something common at all in REST APIs. If you want to submit a PR implementing this functionality, you are more than welcome.

ok,I will try,but could you tell me where the sent request function is(I think it will alleviate my work thanks
