### ISSUE TITLE
RestTest execution stucks in Predicate test

### ISSUE THREAD

**Issue by mspsoft** [isa-group/RESTest#231]
Hello,
I have setup the RESTTest and done below changes
1. public class CreateTestConf {

    private static final Logger log = LogManager.getLogger(CreateTestConf.class);
    private static String openApiSpecPath = "src/test/resources/Restcountries/openapi.yaml";

2.restcountries_demo_properties
# OAS specification
oas.path=src/test/resources/Restcountries/openapi.yaml

3.public class TestGenerationAndExecution {

	// Properties file with configuration settings
	private static String propertiesFilePath = "src/test/resources/Restcountries/restcountries_demo.properties";

Now I am executing the TestGenerationAndExecution from eclipse.

The execution stucks [INFO] Running es.us.isa.restest.inputs.semantic.PredicatesTest

<img width="576" alt="resttestexecution" src="https://user-images.githubusercontent.com/12424070/210999523-a2723bc9-9b03-4851-b7fc-1d6b0649a4e3.png">

Can anyone guide me how to overcome this issue.

Thanks,
Mahesh patil

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Hi,

I just executed the same classes by using the same files and it works perfectly. Did you apply any changes to the .properties file or the testConfiguration file?

**Comment by mspsoft** [comment]
Hello,
Thanks for reply. I have done the setup now. there were some packages missing, this issue is resolved.
I am able to run the project successfully. 

Now the problem is that all the test cases are failing, I checked for Bikewise and restcountries.

Can you help me in setting up any small API where I can see some test cases passing.

I would be happy to setup a google meet if you can spare some time.

Thanks a lot for your help.

Thanks,
MAehsh Patil
![image](https://user-images.githubusercontent.com/12424070/212280565-2c06506b-c8c5-4d9d-aaaa-969f6f0d3833.png)

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Could you send me the content of both the oas-specification/swagger and the testConf so I can see where the problem may be?
