### ISSUE TITLE
(Suggestion): Document required Java version

### ISSUE THREAD

**Issue by luebbert42** [isa-group/RESTest#232]
I tried to get the system up and running with the latest openjdk version (17). Not coming from the java world it took me some time before I realized that my problems (error messages about not existing groovy classes, the logger, problems with the javadoc step...) where coming from not using the right Java version. When I started a new container with java-8-jdk the instructions in the Readme.md started to work perfectly. :-)

Maybe you want to consider to add the supported Java versions in a requirements section in the Readme?

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Hi,

Thank you for your suggestion, we are currently working on a new RESTest release. We will add a new installation guide once it is ready.

**Comment by luebbert42** [comment]
I also struggled to run the TestGenerationAndExecution.java class after editing it via command line.

# this works and creates the huge jar file
mvn clean install -DskipTests

# this does not work, but maybe this is not intended at all to work
mvn  -X compile exec:java -Dexec.mainClass="es.us.isa.restest.main.TestGenerationAndExecution"
 
 When I tried this, ClassLoader.loadClass in RESTestRunner.java failed to load the generated test class properly as the import statements in the generated class fail(does not find the junit jar for example though everything is in place in the maven repo). 
As a Java noob I did not manage to fix that. 

Finally I installed Intellij and this worked for me. 🚀 
If this is the way to go this could be also explained more in detail for other Java noobs. :-)
