### ISSUE TITLE
Missing maven dependencies

### ISSUE THREAD

**Issue by WardDG** [isa-group/RESTest#233]
I could be wrong but I think some of the dependencies in the pom.xml file might be out of date.  The following 4 dependencies all give the error "no dependency information available" when trying to execute "mvn install":

		<dependency>
			<groupId>es.us.isa</groupId>
			<artifactId>idlreasoner-choco</artifactId>
			<version>1.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>es.us.isa</groupId>
			<artifactId>idl-choco</artifactId>
			<version>1.0.0</version>
		</dependency>

		
		<dependency>
			<groupId>es.us.isa</groupId>
			<artifactId>MaleRegexTree</artifactId>
			<version>1.0.0</version>
		</dependency>

		<dependency>
			<groupId>es.us.isa</groupId>
			<artifactId>RandomRegexTurtle</artifactId>
			<version>1.0.0</version>
		</dependency>

I think I found the updated versions of the first two (please correct me if these are not correct):

		<dependency>
			<groupId>es.us.isa</groupId>
    		<artifactId>idl-reasoner</artifactId>
    		<version>0.0.2</version>
		</dependency>

		
		<dependency>
			<groupId>es.us.isa</groupId>
    		<artifactId>idl</artifactId>
    		<version>0.0.1</version>
		</dependency>

But I've not been able to find the "MaleRegexTree" or "RandomRegexTurtle" anywhere in the maven repository.

**Comment by WardDG** [comment]
Ok, I managed to figure out that the "./scripts/install_dependencies.sh" apparently doesn't work in powershell, but it does in git bash. This fixed the issue and allowed "mvn install" to go through, although it did give these errors, is that normal?
![image](https://user-images.githubusercontent.com/48056138/218510120-92e3d789-07f9-4154-8de1-6a16ecc028a2.png)

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Hi,
The dependencies in the original pom.xml file are correct, idlreasoner-choco and idl-choco are the updated versions of idlreasoner and idl, respectively, make sure to execute the “install_dependencies.sh” script before running “mvn install”. 

If you still get the “BUILD FAILURE” error message after following these steps, please let me know which Java version are you using.

**Comment by WardDG** [comment]
Tested around a bit more, I found that running it with administrator permissions seem to have fixed most of the errors, although none of the failures, now I only have these:
![image](https://user-images.githubusercontent.com/48056138/221566464-7d91e63b-d796-4f87-abf6-a4d646bd1301.png)
my java version is openjdk 1.8. It is important to note that it only seems to go wrong during testing and the actual maven dependencies seem to be installed correctly, since I've been using restest for nearly 2 weeks now without seemingly any issues. 

These are the error messages from where the failures appear:
![image](https://user-images.githubusercontent.com/48056138/221568693-2bcd0f72-ce87-41d0-9eca-b1a6ea5603e0.png)
![image](https://user-images.githubusercontent.com/48056138/221568733-9c05cc1d-6a84-4b69-8e5d-af96eb9935e1.png)
![image](https://user-images.githubusercontent.com/48056138/221568803-7ca55fa7-8e44-4629-aed9-d45407b79de7.png)

**Comment by JuanCarlosAlonsoValenzuela** [comment]
Thank you for reporting this, I will check and update the test cases.
