### ISSUE TITLE
Create a new Writer to use PITest

### ISSUE THREAD

**Issue by josferde5** [isa-group/RESTest#38]
PITest does not execute the tests generated by the RESTAssuredWriter because it does not detect any code execution in the APIs.

The easiest solution is to create a new Writer which turns the test cases into a JUnit test suite that explicitly calls methods of the APIs.

**Comment by AML14** [comment]
This is outdated. The actual way we should use PITest is not by calling the class methods, but running the API in the same JVM where the tests are executed, e.g., using Spring.
