### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by virmacrom** [isa-group/RESTest#68]
By following the steps indicated for setting up RESTest, we have detected that in step 2, the CreateTestConf class is referenced, which does not currently exist in the project, so we suggest that the update of the README file, since it can cause confusion when we configurate the project.

**Comment by josferde5** [comment]
The CreateTestConf class is a part of a new feature that we are currently implementing. It will be finished and released in a few days, so we will update the README file to properly reference the class immediately after that.

**Comment by josferde5** [comment]
README updated. Closing ticket.
