### ISSUE TITLE
Explore the possibility of applying Diversity Search to generate tests suites

### ISSUE THREAD

**Issue by japarejo** [isa-group/RESTest#73]
https://medium.com/@nniranjhana/on-genetic-algorithms-why-novelty-search-is-important-6d2879d3ed81

Probably this can be applied to support the creation of valid test suites with high coverage.
Additionally , we should do some research on the algorithms used to support this kind of search and their availability in JMetal.

**Comment by AML14** [comment]
Interesting! I had a couple of ideas while reading the article:
  - We could start creating test suites focusing on the inputs, e.g., focusing on diversity or input coverage (which do not require the execution of test cases and hence they are fast to generate) and then start applying different objective functions such as "output coverage" or "error messages".
  - We could consider using different algorithms besides NSGAII. Arcuri, for instance, uses [MIO](https://arxiv.org/abs/1901.01541).

**Comment by AML14** [comment]
Outdated.
