### ISSUE TITLE
New stopping criterion: number of executed requests (test cases)

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#83]
When comparing random VS search-based, it seems more fair to consider the total number of executed tests, and not the total number of evaluations.

**Comment by japarejo** [comment]
I tried to overwrite the isStoppingConditionReached() method of NSGAII, however this approach was not consistent with the interface of the RandomSearch algorithm provided by JMetal (it is an internal consistency of the framework, that does not impos an homogeneous approach to termination criterions) thus I had to create alternative implementations of the algorithms under a common and consistent interface.
