### ISSUE TITLE
Preconditions fail with Stripe formData parameters

### ISSUE THREAD

**Issue by AML14** [isa-group/RESTest#85]
It is due to the parameter name "attributes[]", which in OAS is called "attributes" and declared as an object.

![image](https://user-images.githubusercontent.com/17610593/86034341-b07be300-ba3a-11ea-8a1f-3958efdb947b.png)

**Comment by josferde5** [comment]
Both #84 and #85 are now fixed, but I have found that the Atlassian OAI validator does not support formData parameters with encoding. We will have to use the Swagger 2.0 spec to test the Stripe API for now.
